export const courses = [
  {
    id: 1,
    category: { color: "#FF3864", id: 3, text: "Tecnologia" },
    img: "/bg3.png",
    price: 1500,
    stars: 4.5,
    text: "Frontend Developer",
    url: "/frontend",
    freeTax: 3,
    taxes: 5,
  },
  {
    id: 2,
    category: { color: "#FF3864", id: 3, text: "Tecnologia" },
    img: "/blog3.webp",
    price: 1,
    stars: 5,
    text: "Backend",
    url: "/backend",
    freeTax: 3,
    taxes: 5,
  },
  {
    id: 3,
    category: { color: "#48E5C2", id: 1, text: "Empresa" },
    img: "/blog1.webp",
    price: 200,
    stars: 5,
    text: "Dropshiping",
    url: "/dropshipping",
    freeTax: 3,
    taxes: 5,
  },
  {
    id: 4,
    category: { color: "#F39C6B", id: 2, text: "Marketing" },
    img: "/bg2.webp",
    price: 1,
    stars: 5,
    text: "Social Media",
    url: "/instagram",
    freeTax: 3,
    taxes: 5,
  },
  {
    id: 5,
    category: { color: "#F39C6B", id: 2, text: "Marketing" },
    img: "/bg1.jpeg",
    price: 100,
    stars: 5,
    text: "Youtube",
    url: "/youtube",
    freeTax: 1,
    taxes: 10,
  },
];
